### ISSUE TITLE
Some console errors.

### ISSUE THREAD

**Issue by spearsonwork** [microsoftgraph/msgraph-training-angularspa#21]
A minor point, but due to some asynchronicity you could add some *ngIf guard clauses so that displayName/avatar is only read once authService.user has been returned by the authService to get rid of these annoying console errors:
```
ERROR TypeError: Cannot read property 'displayName' of undefined
    at Object.eval [as updateRenderer] (HomeComponent.html:6)
```
```
ERROR TypeError: Cannot read property 'avatar' of undefined
    at Object.eval [as updateDirectives] (NavBarComponent.html:26)
```

**Comment by jasonjoh** [comment]
Thanks @spearsonwork! We do accept pull requests ;)
