### ISSUE TITLE
"user_cancelled|User closed the popup window and cancelled the flow"

### ISSUE THREAD

**Issue by adamraetz** [microsoftgraph/msgraph-training-angularspa#22]
Error  occurs the moment I click on: Click here to sign in.

Once logged (the pop up to select Microsoft account does appear) in it will loop back to a logging in. 

No compiler errors. Running in Edge.

**Comment by jasonjoh** [comment]
Did you download the project from GitHub, download from our [quick-start page](https://developer.microsoft.com/graph/quick-start?platform=option-angular), or are you following the [tutorial](https://docs.microsoft.com/graph/tutorials/angular)?

Also, what type of account are you using to login? Is it a Microsoft 365 account (work or school) or a personal account (like Outlook.com)?

**Comment by adamraetz** [comment]
I have actually done all 3. I initially followed the tutorial manually.
Then I downloaded from the various spots.

All outcomes are the same.

**Comment by jasonjoh** [comment]
@adamraetz did you have a chance to try my suggestions above? Let me know if you still need help with this.

**Comment by jasonjoh** [comment]
Closing due to no response.
