### ISSUE TITLE
Issue with @azure/msal-angular 0.1.4 using Angular 9.0.2

### ISSUE THREAD

**Issue by SA-David** [microsoftgraph/msgraph-training-angularspa#27]
When adding in the import below:

    MsalModule.forRoot({
      clientID: OAuthSettings.appId
    })

the following error is thrown:

    ERROR in node_modules/@azure/msal-angular/dist/msal.module.d.ts:6:41 - error NG6005: MsalModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.

Cheers

**Comment by jasonjoh** [comment]
Are you following along with the tutorial? I'm guessing this is a version thing, since the tutorial was written with Angular 8.2.

This tutorial/sample is on my refresh list in the coming weeks.

**Comment by SA-David** [comment]
Thanks for your reply, Jason.

Yes I'm following the tutorial. I have now gone back to Angular 8.2.14 and the error is no longer there. Would be great to see a refresh tutorial soon.

Cheers,

Dave

**Comment by jasonjoh** [comment]
Refreshed version (see #28) uses Angular 9.x
